# Generated by Django 4.2.13 on 2024-05-11 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_user_delete_authen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=10, null=True)),
                ('l_name', models.CharField(blank=True, max_length=10, null=True)),
                ('full_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='doctor01/%y/%m/%d')),
                ('content', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Geriatric_medicine_doctors', 'Geriatric_medicine_doctors'), ('Infectious_disease_doctors', 'Infectious_disease_doctors'), ('Urologists', 'Urologists'), ('Neurologists', 'Neurologists'), ('General_surgeons', 'General_surgeons'), ('Cardiac_surgeons', 'Cardiac_surgeons'), ('Orthopedic_surgeons', 'Orthopedic_surgeons')], max_length=50, null=True)),
                ('added_at', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=10, null=True)),
                ('l_name', models.CharField(blank=True, max_length=10, null=True)),
                ('full_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(upload_to='patient01/%y/%m/%d')),
                ('added_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
