# Generated by Django 4.2.13 on 2024-06-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_completed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
